displayName=Collection Log Hider
author=mattjrumble
support=https://github.com/mattjrumble/collection-log-hider-plugin
description=Hide obtained items and completed sections from the collection log
tags=collection,log,clog,hide,hider
plugins=com.collectionloghider.CollectionLogHiderPlugin
build=standard